### ISSUE TITLE
Sortkey should be joined by comma

### ISSUE THREAD

**Issue by m1hawkgsm** [jucyai/red-panda#2]
On this line https://github.com/jucyai/red-panda/blob/1792dc615dd5da6104091d5711a9d82a8725a4d6/red_panda/red_panda.py#L377 , you join with a space, but the definition of the `CREATE TABLE` command https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_examples.html requires comma separated columns.  I got around this by just pre-pending each column with a comma, but obvious bug.

**Comment by yaojiach** [comment]
@m1hawkgsm Thanks for pointing out the bug.
