### ISSUE TITLE
Specify stricter dependencies in Pipfile

### ISSUE THREAD

**Issue by m1hawkgsm** [jucyai/red-panda#3]
**Is your feature request related to a problem? Please describe.**
This isn't necessary a bug (hence why I chose feature request) but also not much of a feature, just a suggestion.  My team currently uses Poetry to manage our library builds, and we've noticed adding `red-panda` increases the tool's dependency's resolution time exponentially (literally hours, actually have not been able to make it work so far). Looking a bit deeper, I see that it's probably due to the fact your `Pipfile` dependencies are all wildcards.

**Describe the solution you'd like**
If possible, and not _too_ big of a lift, could you provide some more meaningful restrictions on dependency versions? Anything but `*` would likely be helpful.

More generally, even though adding restrictions might seem an "extra", in my experience it's helpful down the line when you might encounter annoying conflicts (you know what you have, and what you can and/or should change).

**Describe alternatives you've considered**
-  *Not including this in our build*: Works but it's obviously not what we'd want!
-  *Not using Poetry*:  Have only tried running with classic `setuptools` but we lose a good deal of sane safeguards without a tool like this. Have not tried Pipenv yet (may consider it and working that possibility separately), but my above point still holds.

Thanks for your time, and for the work put into this, quite helpful!

**Comment by yaojiach** [comment]
@m1hawkgsm thanks for opening this. I realize it is also still taking quite some time (~ 2 minutes) to resolve dependencies when installed with pipenv. I'm trying to pinpoint the exact issue. Once this is fixed, I am going to release a 1.0.0b1 version with other improvements.

**Comment by yaojiach** [comment]
@m1hawkgsm if you have time, would you mind trying the dev branch in your project build? I tried with pipenv and it took under three minutes to install package and resolve/lock dependencies.

**Comment by m1hawkgsm** [comment]
Apologies, my notifications didn't work for this.  I just tried and can confirm this is working beautifully well. Looks good!

**Comment by yaojiach** [comment]
Thank you. I will release this once I complete improvements in testing and docs.
